home/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('iisma-assignment1/', views.iismaassignment1, name='iisma-assignment1'),
]

web_ardha/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

def iismaassignment1(request):
    return render(request, 'home/iisma-assignment1.html')

home/templates/home/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Ardha's Personal Website</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'home/css/Qgis2threejs.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}"> {% endcomment %}

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

  <style>
    :root {
      --grey: #e4e4e4;
      --blue: #005aa4;
      --white: #ffffff;
    }
    
    /* Temporary */
    .ass {
      color: black;
      background: rgb(222, 222, 222);
      transition: all .3s;
    }

    .ass:hover {
      color: black;
      background: rgb(188, 188, 188);
      transition: all .3s;
    }
    /* Temporary */

    html {
      position:relative; 
      min-height: 100%;
    }
    
    body {
      font-family: arial, sans-serif;
      margin: 0;
    }
    
    .header {
      background-color: var(--grey);
    }
    
    footer {
      position: absolute;
      bottom: 0;
      background: var(--grey);
    }
    
    .course p {
      color: var(--blue)
    }
    
    .comparation-tab img {
      width: 100%;
      height: auto;
    }
    
    .view-title {
      position: absolute;
      top: 130%;
      left: 5%;
    }
    
    .page-menu div {
      height: 40px;
      transition: all .3s;
    }
    
    .page-menu div:hover {
      height: 40px;
      background: rgb(223, 223, 223);
      transition: all .3s;
    }
    
    /* ============== Small Screen ============== */
    
    @media only screen and (max-width: 767px) {
      #layerpanel, #popup {
        left: 12% !important;
      }
    
      #view, #toolbtns, #layerpanel, #popup {
        top: 380%;
      }
    
      .view-title {
        top: 370%;
      }
    }
    
    @media only screen and (max-width: 740px) {
      #view, #toolbtns, #layerpanel, #popup {
        top: 360%;
      }
    
      .view-title {
        top: 350%;
      }
    }
    
    @media only screen and (max-width: 700px) {
      #view, #toolbtns, #layerpanel, #popup {
        top: 350%;
      }
    
      .view-title {
        top: 340%;
      }
    }
    
    @media only screen and (max-width: 650px) {
      #view, #toolbtns, #layerpanel, #popup {
        top: 330%;
      }
    
      .view-title {
        top: 320%;
      }
    }
    
    @media only screen and (max-width: 600px) {
      #view, #toolbtns, #layerpanel, #popup {
        top: 320%;
      }
    
      .view-title {
        top: 310%;
      }
    }
    
    @media only screen and (max-width: 550px) {
      #view, #toolbtns, #layerpanel, #popup {
        top: 260%;
      }
    
      .view-title {
        top: 250%;
      }
    }
    
    @media only screen and (max-width: 500px) {
      #view, #toolbtns, #layerpanel, #popup {
        top: 220%;
      }
    
      .view-title {
        top: 210%;
      }
    }
    
    @media only screen and (max-width: 580px) {
      #layerpanel, #popup {
        left: 16% !important;
      }
    
      #view, #toolbtns, #layerpanel, #popup {
        top: 200%;
      }
    
      .view-title {
        top: 195%;
      }
    }
    
    /* ============== Modal Image View ============== */
    
    .myImages {
      border-radius: 5px;
      cursor: pointer;
      transition: 0.3s;
    }
    
    .myImages:hover {opacity: 0.7;}
    
    /* The Modal (background) */
    .modal {
      display: none; /* Hidden by default */
      position: fixed; /* Stay in place */
      z-index: 1; /* Sit on top */
      padding-top: 40px; /* Location of the box */
      left: 0;
      top: 0;
      width: 100%; /* Full width */
      height: 100%; /* Full height */
      overflow: auto; /* Enable scroll if needed */
      background-color: rgb(0,0,0); /* Fallback color */
      background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
    }
    
    /* Modal Content (image) */
    .modal-content {
      margin: auto;
      display: block;
      width: 100%;
      max-height: 80vh;
      max-width: 700px;
    }
    
    /* Caption of Modal Image */
    #caption {
      margin: auto;
      display: block;
      width: 80%;
      max-width: 700px;
      text-align: center;
      color: #ccc;
      padding: 10px 0;
      height: 150px;
    }
    
    /* Add Animation */
    .modal-content, #caption {  
      -webkit-animation-name: zoom;
      -webkit-animation-duration: 0.3s;
      animation-name: zoom;
      animation-duration: 0.3s;
    }
    
    @-webkit-keyframes zoom {
      from {-webkit-transform:scale(0)} 
      to {-webkit-transform:scale(1)}
    }
    
    @keyframes zoom {
      from {transform:scale(0)} 
      to {transform:scale(1)}
    }
    
    /* The Close Button */
    .close {
      position: absolute;
      z-index: 999;
      top: 15px;
      right: 35px;
      color: #f1f1f1;
      font-size: 40px;
      font-weight: bold;
      transition: 0.3s;
    }
    
    .close:hover,
    .close:focus {
      color: #bbb;
      text-decoration: none;
      cursor: pointer;
    }
    
    /* 100% Image Width on Smaller Screens */
    @media only screen and (max-width: 700px){
      .modal-content {
        width: 100%;
      }
    
  </style>
</head>

<body>
  <div class="header p-3 m-0 row">
    <!-- Menu Button -->
    <button class="btn btn-secondary col-1 my-auto" style="width: min-content;" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions"><i class="bi bi-list"></i></button>

    <!-- Off Canvas -->
    <div class="offcanvas offcanvas-start" style="max-width: 320px;" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">Menu</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <img class="mb-3 rounded-circle mx-auto d-block" style="height: 20%;" src="https://cdn.discordapp.com/attachments/925303244245307432/1024300564630216735/profile.JPG" alt="Ardha's Profile Photo">
        <div class="text-center">
          <h5 class="m-0">Ardha Irfan Hakim</h5>
          <p class="m-0">3098826</p>
          <p>Faculty of ITC, University of Twente</p>
          <a href="/" class="btn btn-secondary border-0" target="_self">Home</a>
        </div>
        <div class="course my-4">
          <div class="page-menu">
            <h6>Geographic Information Systems</h6>
            <a class="text-dark" href="{% url 'home:iisma-assignment1' %}" style="text-decoration: none; font-weight: 400;" target="_self">
              <div class="row d-flex align-items-center ms-2">
                <p class="m-0">Assignment 1: LiDAR Tutorial</p>
              </div>
            </a>
            {% comment %} <a class="text-dark" href="/" style="text-decoration: none; font-weight: 500;" target="_self"> {% endcomment %}
              <div class="row d-flex align-items-center ms-2 opacity-50">
                <p class="m-0">Assignment 2</p>
              </div>
            {% comment %} </a> {% endcomment %}
            {% comment %} <a class="text-dark" href="/" style="text-decoration: none; font-weight: 500;" target="_self"> {% endcomment %}
              <div class="row d-flex align-items-center ms-2 opacity-50">
                <p class="m-0">Assignment 3</p>
              </div>
            {% comment %} </a> {% endcomment %}
          </div>
        </div>
      </div>
    </div>

    <!-- Header -->
    <div class="col">
      <h1>Ardha Irfan Hakim</h1>
      <h6>Faculty of ITC, University of Twente</h6>
    </div>
    <!-- <div class="col-12 col-md-5 text-end my-auto">
      <h4 class="align-middle text-success">Assignment 1</h4>
    </div> -->
  </div>

  <main>
    <a class="text-center" href="/iisma-assignment1" style="text-decoration: none;">
      <div class="ass col-4 mx-auto my-5 p-5" style="height: 20%;">
        <h5>Assignment 1</h5>
      </div>
    </a>
  </main>

  <!-- The Modal -->
  <div id="myModal" class="modal">
    <span class="close"><i class="bi bi-x-circle-fill"></i></span>
    <img class="modal-content" id="img01">
    <div id="caption"></div>
  </div>

  <footer class="p-3 col-12">
    <p class="text-center">2022 &copy; Copyright Ardha Irfan Hakim<p>
  </footer>

  <script>
    // create references to the modal...
    var modal = document.getElementById('myModal');
    // to all images -- note I'm using a class!
    var images = document.getElementsByClassName('myImages');
    // the image in the modal
    var modalImg = document.getElementById("img01");
    // and the caption in the modal
    var captionText = document.getElementById("caption");

    // Go through all of the images with our custom class
    for (var i = 0; i < images.length; i++) {
      var img = images[i];
      // and attach our click listener for this image.
      img.onclick = function(evt) {
        modal.style.display = "block";
        modalImg.src = this.src;
        captionText.innerHTML = this.alt;
      }
    }

    var span = document.getElementsByClassName("close")[0];

    span.onclick = function() {
      modal.style.display = "none";
    }
  </script>

  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

</body>

</html>